### ISSUE TITLE
Column Names

### ISSUE THREAD

**Issue by rmeske** [moodleou/moodle-report_customsql#136]
When attempting to output column labels that are compatible with a system that is then importing the output, I am finding that the strings being used are being modified.  For example, 'CD_VAL_CD'  outputs as 'cd val cd'.  

Since CONCAT cannot be used to create a label for a column, is there any way to get, at a minimum, the underscores to be used?

**Comment by timhunt** [comment]
This is a featur, not a bug, at least for us. Our goal is to create nice human-readable reports, which is why we replace _ with space in the colunn names to make the table titles.

I think that, if you have a scheduled report, and use the 'Export csv report to path / directory' feature, then you will get the raw CSV files copied to that folder, with the original column names from the database.

**Comment by rmeske** [comment]
Understood.  Just hoped there was a means to have it formatted differently.
