### ISSUE TITLE
Overcoming the 5000 result row limit

### ISSUE THREAD

**Issue by michael-milette** [moodleou/moodle-report_customsql#30]
I am currently working on a site with 75,000 users and would need to override the 5,000 row limit in the results. I know that the recommended approach to this is to modify the locallib.php file and alter the 5000 number however, every time we upgrade the plugin, someone has to remember to go and customize the number again... which only happens reliably in a perfect world.

I would like to propose that there be a check to see if the number was previously defined somewhere else in Moodle - like Moodle's own config.php. This would allow people to customize the limit number by just adding a line similar to the following to their config.php:

    define('REPORT_CUSTOMSQL_MAX_RECORDS', 20000);

At the same time, it would be great to be able to alter the number representing the starting day of the week by adding the following line to Moodle's own config.php too:

    define('REPORT_CUSTOMSQL_START_OF_WEEK', 7); // Sunday.

For your convenience, a pull request with a proposed fix will be coming in a few minutes. It would be most appreciated if this could be included in future releases of the plugin.

The alternative solution would be to create a settings page for the plugin where these values could be customized.

Let me know if you have any questions or concerns.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
A pull request, #31 , is now available to address this issue.

**Comment by timhunt** [comment]
If we are going to do this, we should do it properly, with real admin settings defined in settings.php. So I am afraid I don't want to merge this patch.

See comments on pull requests #28 and #31 for more.

**Comment by adpe** [comment]
This PR #63 should add this functionality and also to set the default to a custom value.

**Comment by timhunt** [comment]
This is now done in the latest release.

**Comment by DimitriosA** [comment]
I have a similar issue using report_customsql 4.2 for Moodle 3.9+ on my Moodle 4.3.3. platform like the one michael-milette mentioned above and according to your comments I've changed the corresponding values in the configuration file /moodle/report/customsql/settings.php as following: 

get_string('querylimitdefault_desc', 'report_customsql'), 25000, PARAM_INT, null, 10));
get_string('querylimitmaximum_desc', 'report_customsql'), 25000, PARAM_INT, null, 10));

but after restarting the php-service on the moodle server the issue is still not solved, i.e. I got the same error message again: 

“This query reached the limit of 5000 rows. Some rows may have been omitted from the end.”

Are there further changes necessary to get more than 5000 result rows from my sql query?

**Comment by timhunt** [comment]
Each query has a limit set in its setting. I assuem you have not edited teh query to change that.

**Comment by DimitriosA** [comment]
I've tried to change the limit in the query itself,  i.e. I've set it to 25000 but the new value has been rejected due to the error message:

"Number must be between 1 and 5000"

It seems that the corresponding parameter querylimitrange is still limited to 5000, although it should be accept  values up to 25000, the new value of “querylimitmaximum” according to the settings in 
/data/www/html/moodle/report/customsql/edit_form.php 
…
// Check querylimit is in range.
        $maxlimit = get_config('report_customsql', 'querylimitmaximum');
        if (empty($data['querylimit']) || $data['querylimit'] > $maxlimit) {
            $errors['querylimit'] = get_string('querylimitrange', 'report_customsql', $maxlimit);
        }
…

**Comment by timhunt** [comment]
Just editing settings.php won't change the value in your Moodle site. Go to Admin -> Plugins -> reports -> Ad-hoc DB queries, and set the value you want there.

**Comment by DimitriosA** [comment]
That did the trick! 
Thank you very much Tim
