### ISSUE TITLE
Enable using external database for reporting

### ISSUE THREAD

**Issue by logan-reynolds** [moodleou/moodle-report_customsql#32]
We have a client who loves the Custom SQL reports plugin, but due to running extremely large and/or complex queries it is causing performance problems and site downtime when they use it.  This feature request is to allow an option for using an external database which holds a copy of the site data, that way server-intensive queries wouldn't affect the production site and instead run on the replicated copy.

**Comment by timhunt** [comment]
That is a sensible suggestion, and if you can think of a good way to manage the configuration, I would be delighted to accept a pull request for this. However, I don't have time to develop it myself.

**Comment by imatotek** [comment]
Maybe if you could upgrade plugin to work with external log database, because Moodle creates very large log tables and we have moved logging to external database and we can't use this plugin because I can create query only on standard Moodle database. 
Thank you.

**Comment by timhunt** [comment]
Note that, since Moodle 3.9, we have had https://tracker.moodle.org/browse/MDL-19711. With that, reports are run against the read replica - if you have set that up. I think that is a much better and more general solution to the issue raised here, and I don't think the suggestion here is ever going to happen, so I am going to close this.
